version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: LimasIotDevices.API/Dockerfile
    ports:
      - "${HOST_PORT:-8080}:8080"
    environment:
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
      HOME_ASSISTANT_HOST_URL: ${HOME_ASSISTANT_HOST_URL}
      HOME_ASSISTANT_TOKEN: ${HOME_ASSISTANT_TOKEN}
      DEVICE_EVENT_DEBOUNCE_MILLISECONDS: ${DEVICE_EVENT_DEBOUNCE_MILLISECONDS:-3000}
